# Generated by Django 4.2.23 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.TextField(help_text='Use {{column_name}} placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
